/**
 * Compute the $95,000 take-home figure the state-page FAQ asks for, in every
 * jurisdiction, using the engine rather than an estimate.
 *
 * The FAQ question "How much of a $95,000 salary do you keep in {State}?" shipped
 * as a PENDING_ENGINE placeholder because writing a plausible number would break
 * rule 5-3. The engine exists and is tested to the cent, so the honest fix is to
 * run it — 51 real answers instead of 51 placeholders.
 *
 * Output: data/takehome-95k.json, consumed by scripts/generate_onpage.py.
 */
import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { estimateTax, type EngineData } from "../src/lib/tax/index.js";
import { loadEstimated, loadFederal, loadState } from "../src/lib/tax/load.js";
import type { TaxInput } from "../src/lib/tax/types.js";

const YEAR = 2026;
const SALARY = 95_000;

const federal = loadFederal(YEAR);
const estimated = loadEstimated(YEAR);

const statesDir = path.join(process.cwd(), "src/data/tax-year-2026/states");
const slugs = readdirSync(statesDir)
  .filter((f) => f.endsWith(".json"))
  .map((f) => f.replace(/\.json$/, ""))
  .sort();

const input: TaxInput = {
  taxYear: YEAR,
  filingStatus: "single",
  businessIncome: SALARY,
};

const out: Record<string, unknown> = {};
for (const slug of slugs) {
  const state = loadState(YEAR, slug);
  const data: EngineData = { federal, estimated, state };
  const r = estimateTax(input, data);

  // The engine returns a null state tax for the nine no-tax jurisdictions; the
  // difference against a no-state-tax baseline is what the page actually compares.
  const baseline = estimateTax(input, { federal, estimated, state: null });

  out[slug] = {
    name: state.name,
    structure: state.structure,
    grossProfit: SALARY,
    totalTax: round(r.totalTax),
    takeHome: round(r.takeHome),
    stateTax: round(r.totalTax - baseline.totalTax),
    effectiveRate: +((r.totalTax / SALARY) * 100).toFixed(1),
    warnings: r.warnings ?? [],
  };
}

function round(n: number) {
  return Math.round(n * 100) / 100;
}

writeFileSync(
  "data/takehome-95k.json",
  JSON.stringify(
    {
      $comment:
        "GENERATED by scripts/compute_takehome.ts using the tax engine. Do not edit " +
        "by hand. Single filer, $95,000 of self-employment profit, no other income " +
        "or deductions. Regenerate after any dataset change.",
      taxYear: YEAR,
      scenario: { filingStatus: "single", businessIncome: SALARY },
      states: out,
    },
    null,
    2,
  ) + "\n",
);

const values = Object.values(out) as Array<{ name: string; takeHome: number }>;
const sorted = [...values].sort((a, b) => b.takeHome - a.takeHome);
console.log(`computed ${values.length} jurisdictions at $${SALARY.toLocaleString()}`);
console.log(`best:  ${sorted[0].name} $${sorted[0].takeHome.toLocaleString()}`);
console.log(`worst: ${sorted[sorted.length - 1].name} $${sorted[sorted.length - 1].takeHome.toLocaleString()}`);
console.log(`spread: $${(sorted[0].takeHome - sorted[sorted.length - 1].takeHome).toLocaleString()}`);
