/**
 * The figures a metro page quotes, computed by the engines from the real
 * datasets rather than typed into copy:
 *
 *   household   HUD Fair Market Rent for the bedroom count, plus the BLS
 *               national average spending for a household of that size in each
 *               everyday category, priced at the metro's BEA price parity.
 *   salary      the gross salary that leaves exactly that much after federal
 *               tax, FICA and the state's income tax (single filer for one
 *               person; married filing jointly for four).
 *
 * It covers the categories listed and nothing else — no savings, insurance
 * premiums beyond health, or debt — and the copy says so.
 *
 * Output: data/metro-figures.json, read by scripts/generate_onpage.py.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { cityMonthlyCost, grossForNet, type PlaceCostData, type SpendingBaseline } from "../src/lib/col/index.js";
import type { EngineData } from "../src/lib/tax/index.js";
import { loadEstimated, loadFederal, loadState } from "../src/lib/tax/load.js";
import { toCents, toDollars } from "../src/lib/tax/money.js";
import { estimateWageTakeHome } from "../src/lib/tax/payroll.js";
import type { FilingStatus } from "../src/lib/tax/types.js";

const TAX_YEAR = 2026;
const dir = "src/data/cost-of-living-2024/us";
const baseline: SpendingBaseline = JSON.parse(readFileSync("src/data/ces-2024/baseline.json", "utf8"));
const federal = loadFederal(TAX_YEAR);
const estimated = loadEstimated(TAX_YEAR);

const scenarios = [
  { key: "single", people: 1, bedrooms: 1, filingStatus: "single", children: 0 },
  { key: "family", people: 4, bedrooms: 2, filingStatus: "marriedJointly", children: 2 },
] as const;

const out: Record<string, unknown> = {};
for (const file of readdirSync(dir).filter((f) => f.endsWith(".json")).sort()) {
  const place: PlaceCostData = JSON.parse(readFileSync(path.join(dir, file), "utf8"));
  const tax: EngineData = { federal, estimated, state: loadState(TAX_YEAR, place.stateSlug!) };
  const row: Record<string, unknown> = { indices: place.indices, dataYear: place.dataYear };
  for (const s of scenarios) {
    const cost = cityMonthlyCost({
      place, householdSize: s.people, bedrooms: s.bedrooms, baseline,
    });
    const requiredNet = toCents(cost.annualTotal);
    const netAt = (g: number) =>
      toCents(estimateWageTakeHome(
        { taxYear: TAX_YEAR, filingStatus: s.filingStatus as FilingStatus, annualWages: toDollars(g),
          qualifyingChildren: s.children },
        tax).netPay);
    const gross = grossForNet(requiredNet, netAt);
    row[s.key] = {
      people: s.people,
      bedrooms: s.bedrooms,
      filingStatus: s.filingStatus,
      monthlyTotal: cost.monthlyTotal,
      monthlyRent: cost.rows.find((r) => r.key === "rent")!.monthly,
      annualAfterTax: cost.annualTotal,
      grossSalary: toDollars(gross),
      rows: cost.rows.map((r) => ({ key: r.key, label: r.label, monthly: r.monthly })),
    };
  }
  out[place.slug] = row;
}

writeFileSync("data/metro-figures.json", JSON.stringify({
  $comment: "GENERATED by scripts/compute_metro_figures.ts from BEA RPP, HUD FMR and BLS CE data. Do not edit by hand.",
  taxYear: TAX_YEAR,
  baselineYear: baseline.year,
  metros: out,
}, null, 2) + "\n");
for (const [slug, r] of Object.entries(out) as [string, any][]) {
  console.log(slug.padEnd(18), "single", r.single.monthlyTotal, "->", r.single.grossSalary,
              "| family", r.family.monthlyTotal, "->", r.family.grossSalary);
}
