#!/usr/bin/env python3
"""Import HUD Fair Market Rents for every US county.

HUD's own site is unreachable from the build environment, but the policyengine-us
package — the same upstream the state tax data comes from — bundles HUD's published
county-level FMR file for FY2025 and FY2026, together with the Census county FIPS
names. This reads both straight out of the wheel, so every rent on the site is a HUD
figure and every county name a Census one; nothing is typed in.

It is a secondary copy of a primary dataset, so the output carries
"verification": "pending" like the tax data, and should be spot-checked against the
HUD FMR lookup before launch.

    PE_WHEEL=/path/to/policyengine_us-*.whl python3 scripts/import_hud_fmr.py --year 2026

Writes src/data/rent-fy{year}/fmr-counties.json.
"""
import argparse
import csv
import datetime
import gzip
import io
import json
import os
import pathlib
import statistics
import sys
import zipfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
FMR = "policyengine_us/parameters/gov/hud/fmr/fair_market_rents.csv"
NAMES = "policyengine_us/data/county_fips_2020.csv.gz"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--year", type=int, required=True, help="HUD fiscal year")
    args = ap.parse_args()
    wheel = os.environ.get("PE_WHEEL")
    if not wheel or not pathlib.Path(wheel).exists():
        sys.exit("Set PE_WHEEL to a policyengine_us wheel (pip download policyengine-us --no-deps).")
    z = zipfile.ZipFile(wheel)
    version = next((n.split("-")[1] for n in z.namelist() if n.endswith(".dist-info/METADATA")), "?")

    names = {}
    with gzip.open(io.BytesIO(z.read(NAMES)), "rt") as fh:
        for row in csv.DictReader(fh):
            names[row["county_fips"]] = (row["state"], row["county_name"])

    # FMR area code = 5-digit county FIPS (leading zero dropped) + 5-digit
    # subdivision. "99999" is the whole county; anything else is a New England
    # town area, several of which can share one county.
    areas = {}
    with io.TextIOWrapper(z.open(FMR)) as fh:
        for row in csv.DictReader(fh):
            if int(row["year"]) != args.year:
                continue
            code = row["hud_fmr_area_code"].zfill(10)
            fips, sub = code[:5], code[5:]
            areas.setdefault(fips, {}).setdefault(sub, {})[int(row["bedrooms"])] = float(row["value"])

    counties, split, unnamed = {}, [], []
    for fips, subs in sorted(areas.items()):
        state, name = names.get(fips, (None, None))
        if name is None:
            unnamed.append(fips)   # e.g. Connecticut planning regions, not in the 2020 list
            continue
        if list(subs) == ["99999"]:
            rent = subs["99999"]
            counties[fips] = {"state": state, "name": name,
                              "rent": {f"bedrooms{b}": v for b, v in sorted(rent.items())}}
        else:
            # Several town-level areas in one county: publish the range, never a
            # single made-up county figure.
            split.append(fips)
            by_b = {}
            for rent in subs.values():
                for b, v in rent.items():
                    by_b.setdefault(b, []).append(v)
            counties[fips] = {"state": state, "name": name, "rent": None,
                              "townRange": {f"bedrooms{b}": [min(v), max(v)]
                                            for b, v in sorted(by_b.items())},
                              "note": "HUD sets rents by town here; the county has no single figure."}

    out = {
        "$comment": "GENERATED by scripts/import_hud_fmr.py. HUD Fair Market Rents: monthly GROSS "
                    "rent (shelter plus tenant-paid utilities) at the 40th percentile of recent "
                    "movers, by county and bedroom count.",
        "fiscalYear": args.year,
        "source": {"label": f"HUD Fair Market Rents, FY{args.year}",
                   "url": "https://www.huduser.gov/portal/datasets/fmr.html",
                   "via": f"policyengine-us {version} (bundled copy of the HUD county file)",
                   "retrieved": datetime.date.today().isoformat()},
        "verification": "pending",
        "counties": counties,
        "townLevelCounties": split,
        "unnamedAreas": unnamed,
    }
    dest = ROOT / f"src/data/rent-fy{args.year}"
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "fmr-counties.json").write_text(json.dumps(out, indent=1) + "\n")
    single = [c for c in counties.values() if c["rent"]]
    med = statistics.median(c["rent"]["bedrooms1"] for c in single if "bedrooms1" in c["rent"])
    print(f"FY{args.year}: {len(single)} counties with one FMR, {len(split)} town-level, "
          f"{len(unnamed)} unnamed areas skipped · median 1BR ${med:,.0f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
